// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYg04IXKPZTacMk6K64OQXmBJuFd1Aepw',
    appId: '1:837446792148:web:2e5929fc12fcbd9fc95c41',
    messagingSenderId: '837446792148',
    projectId: 'food-delivery-flutter-project',
    authDomain: 'food-delivery-flutter-project.firebaseapp.com',
    storageBucket: 'food-delivery-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMCVhxAE2NT6868y-cVZA_grTNUwcB97E',
    appId: '1:837446792148:android:da51308c3b235af7c95c41',
    messagingSenderId: '837446792148',
    projectId: 'food-delivery-flutter-project',
    storageBucket: 'food-delivery-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuFePXruLiQ-Mol6_OXrG4vhLPM3CvOtw',
    appId: '1:837446792148:ios:11d7983319aa8bd4c95c41',
    messagingSenderId: '837446792148',
    projectId: 'food-delivery-flutter-project',
    storageBucket: 'food-delivery-flutter-project.appspot.com',
    iosClientId: '837446792148-onbu4rneblichsuug6c62suj0qbaphgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDelivery',
  );
}
